### ISSUE TITLE
Various staging area css issues

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1024]
Also, the markup has subtly changed in a way that breaks font size, i think the .p font-size: 1.2rem

![image](https://user-images.githubusercontent.com/124158/83825058-2e500700-a6a6-11ea-9bb4-25a65bb0f60e.png)
![image](https://user-images.githubusercontent.com/124158/83825075-3f991380-a6a6-11ea-9bcc-f1b308d4865c.png)

**Comment by ggeoffrey** [comment]
Unnesting the user domain from the IDE might have affected the cascade, but I'm quite confused since the font size for `p` is in root EMs. What should it look like instead?

Here is the corresponding CSS for reference:
```css
p, .p {
    font-size: 1.2rem; /* intended for typography only (markdown) */
    margin-top: 0;
    margin-bottom: 0; /* twbs sets to 1em */
}
```
