### ISSUE TITLE
IDE topnav spacer that moves the userland down, does not react to changes in topnav height

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#29]
this is highly annoying in practice
![image](https://user-images.githubusercontent.com/124158/35517717-4ba9cb5a-04dd-11e8-9d08-0c8fea8e0ac5.png)

**Comment by khardenstine** [comment]
React16 broke this

**Comment by khardenstine** [comment]
Ripped out the the react ref tracking, and replaced with css grid and overflow-y: auto for user area.

```css
.hyperfiddle-foundation {
    display: grid;
    grid-template-rows: auto 1fr;
    height: 100vh;
}

.hyperfiddle-ide-user {
    grid-row: auto;
    overflow-y: auto;
    will-change: transform;
}

.topnav {
    grid-row: 1;
    z-index: 1;
}
```

Got hit with scroll jank.  Chrome was show my scroll events in the perf recordings, but would refuse to repaint (sometimes for multiple seconds).
My hunch is the problem is overflow-y: auto on a child el, with parent height: 100vh, is the culprit (grid and flex agnostic).

Some resources on paint perf:
https://stackoverflow.com/questions/39261456/reducing-scroll-jank-when-using-overflow-y-scroll
https://www.fourkitchens.com/blog/article/fix-scrolling-performance-css-will-change-property/
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
https://stackoverflow.com/questions/12969228/chrome-slow-scrolling-with-fixed-position-elements
https://stackoverflow.com/questions/25724126/chrome-devtools-timeline-update-layer-tree-event


Ultimately found [`position: sticky`](https://caniuse.com/#search=position%3A%20sticky) and it works like a charm
